import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "./globals.css";
import Sidebar from "@/components/sidebar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "Azimet Kerem Ersoy",
  description: "Generated by Azimet Kerem Ersoy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("h-screen w-full flex", GeistSans.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar />

          <div className="w-full h-full">
            <Navbar />

            <div className="w-full mx-auto h-full">
              <ScrollArea className="h-full max-h-dynamic-screen min-h-dynamic-screen overflow-y-auto overflow-x-hidden relative flex w-full flex-col">
                <div className="z-[1] w-full px-6 pb-8 pt-8 lg:px-8 lg:pb-16 lg:pt-24">
                  <div className="mx-auto w-full lg:mb-0 lg:max-w-3xl">
                    <div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px]"></div>

                    {children}
                  </div>
                </div>
              </ScrollArea>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
